### ISSUE TITLE
Did the weather update break the watchface?

### ISSUE THREAD

**Issue by troubalex** [WinterWinter/KirbyGT#1]
The boss is gone ever since Pebble updated the firmware, and shipped a new weather app. All I see is either the placeholder or The Invisible Boss. 😢 

Unfortunately, I don't speak C, so all I can do to help is buy you a coffee. ☕

**Comment by WinterWinter** [comment]
Hello,

This issue has to do with Openweathermap.org and the API Key provided to
developers for free as it has a limitation of 500 calls per day. I'll be
looking into adding an option to apply your own API key to prevent this
from happening in the future.

Kind regards,
Game Time

**Comment by WinterWinter** [comment]
This issue has now been resolved as of the 1.2 update.

**Comment by troubalex** [comment]
Awesome! Thanks a lot, that was fast. :)
